= Charter (the “Charter”) for Developer Relations Foundation a Series of LF Projects, LLC

Adopted June 3, 2024

This Charter sets forth the responsibilities and procedures for contribution to, and oversight of, the Developer Relations Foundation open collaboration project, which has been established 
as Developer Relations Foundation a Series of LF Projects, LLC (the “Project”).  LF Projects, LLC (“LF Projects”) is a Delaware series limited liability company. All contributors (including 
committers, maintainers, and other administrative positions) and other participants in the Project (collectively, “Collaborators”) must comply with the terms of this Charter. 
:toc:

. **Mission and Scope of the Project** 
.. The mission of the Project is to elevate the professional practice of developer relations and increase awareness of it as a driver of business value. 
.. The scope of the Project includes collaborative development under the Project License (as defined herein) supporting the mission, including definitions, frameworks, and the creation and codification of other artifacts that aid in the mission of the open collaboration project. 
. **Steering Committee** 
.. The Steering Committee (the “SC”) will be responsible for all oversight of the open collaboration Project.  
.. The SC voting members are initially the Project’s Committers. At the inception of the project, the Committers of the Project will be set forth within the “CONTRIBUTING” file within the Project’s code repository. The SC may choose an alternative approach for determining the voting members of the SC, and any such alternative approach will be documented in the CONTRIBUTING file.  Any meetings of the Steering Committee are intended to be open to the public, and can be conducted electronically, via teleconference, or in person.  
.. SC projects generally will involve Contributors and Committers. The SC may adopt or modify roles so long as the roles are documented in the CONTRIBUTING file. Unless otherwise documented:  
... Contributors include anyone in the community that contributes code, documentation, or other artifacts to the Project;  
... Committers are Contributors who have earned the ability to modify (“commit”) source code, documentation or other artifacts in a project’s repository; and
... A Contributor may become a Committer by a majority approval of the existing Committers. A Committer may be removed by a majority approval of the other existing Committers.
... A Collaborator is a member of the community with read and write access to a repository who has been invited to contribute by the SC. 
.. Participation in the Project through becoming a Contributor and Committer is open to anyone so long as they abide by the terms of this Charter.  
.. The SC may (1) establish workflow procedures for the submission, approval, and closure/archiving of projects, (2) set requirements for the promotion of Contributors to Committer status, as applicable, and (3) amend, adjust, refine and/or eliminate the roles of Contributors, and Committers, and create new roles, and publicly document any SC roles,  as it sees fit. 
.. The SC may elect a SC Chair, who will preside over meetings of the SC and will serve until their resignation, term limit,  or replacement by the SC.**   
.. Responsibilities: The SC will be responsible for all aspects of oversight relating to the Project, which may include: 
... coordinating the direction of the Project; 
... approving working groups, with the **initial working groups** expected to cover topics including, but not limited to: 
.... People in the practice: Job descriptions, career foundations, and rubrics. 
.... The practice and programs: Common terminology, frameworks, metrics, and analytics. 
.... Community management: Best practices and initiatives for community building. 
.... Developer Relations Foundation operations: Go-to-market functions, marketing, communication, and administration for the foundation.  
... organizing sub-projects and removing sub-projects; 
... defining roles and other positions and setting criteria and processes on how those roles and positions are filled; 
... creating sub-committees or working groups to focus on cross-project issues and requirements; 
... appointing representatives to work with other open source or open standards communities; 
... establishing community norms, workflows, issuing releases, and security issue reporting policies;  
... approving and implementing policies and processes for contributing (to be 
... published in the CONTRIBUTING file) and coordinating with the series manager of the Project (as provided for in the Series Agreement, the “Series Manager”) to resolve matters or concerns that may arise as set forth in Section 7 of this Charter; 
... discussions, seeking consensus, and where necessary, voting on matters relating to the open collaboration project; and 
... coordinating any marketing, events, or communications regarding the Project. 
. **Voting** 
.. While the Project aims to operate as a consensus-based community, if any decision requires a vote to move the Project forward, the voting members of the SC or Working Group, as applicable, will vote on a one vote per voting member basis and a two-thirds vote of all Members of the SC or Working Group, as applicable, will be required for the vote to pass. 
.. Approval of an item within a Working Group will move the item to the SC for final vote. 
.. In the event a vote cannot be resolved by a Working Group, any voting member of the Working Group may refer the matter to the SC for assistance in reaching a resolution.  In the event a vote cannot be resolved by the SC, any voting member of the SC may refer the matter to the Series Manager for assistance in reaching a resolution. 
. **Compliance with Policies**  
.. This Charter is subject to the Series Agreement for the Project and the Operating Agreement of LF Projects. Contributors will comply with the policies of LF Projects as may be adopted and amended by LF Projects, including, without limitation the policies listed at https://lfprojects.org/policies/.   
.. The SC may adopt a code of conduct (“CoC”) for the Project, which is subject to approval by the Series Manager.  In the event that a Project-specific CoC has not been approved, the LF Projects Code of Conduct listed at [https://lfprojects.org/policies ](https://lfprojects.org/policies)will apply for all Collaborators in the Project. 
.. When amending or adopting any policy applicable to the Project, LF Projects will publish such policy, as to be amended or adopted, on its web site at least 30 days prior to such policy taking effect; provided, however, that in the case of any amendment of the Trademark Policy or Terms of Use of LF Projects, any such amendment is effective upon publication on LF Project’s web site. 
.. All Collaborators must allow open participation from any individual or organization meeting the requirements for contributing under this Charter and any policies adopted for all Collaborators by the SC, regardless of competitive interests. Put another way, the Project community must not seek to exclude any participant based on any criteria, requirement, or reason other than those that are reasonable and applied on a non-discriminatory basis to all Collaborators in the Project community. 
.. The Project will operate in a transparent, open, collaborative, and ethical manner at all times. The output of all Project discussions, proposals, timelines, decisions, and status should be made open and easily visible to all. Any potential violations of this requirement should be reported immediately to the Series Manager. 
. **Community Assets** 
.. LF Projects will hold title to all trade or service marks used by the Project (“Project Trademarks”), whether based on common law or registered rights.  Project Trademarks will be transferred and assigned to LF Projects to hold on behalf of the Project. Any use of any Project Trademarks by Collaborators in the Project will be in accordance with the license from LF Projects and inure to the benefit of LF Projects.   
.. The Project will, as permitted and in accordance with such license from LF Projects, develop and own all Project GitHub and social media accounts, and domain name registrations created by the Project community. 
.. Under no circumstances will LF Projects be expected or required to undertake any action on behalf of the Project that is inconsistent with the tax-exempt status or purpose, as applicable, of the Joint Development Foundation or LF Projects, LLC. 
. **General Rules and Operations.**  
.. The Project will: 
... engage in the work of the Project in a professional manner consistent with maintaining a cohesive community, while also maintaining the goodwill and esteem of LF Projects, Joint Development Foundation and other partner organizations in the open source community; and 
... respect the rights of all trademark owners, including any branding and trademark usage guidelines. 
. **Intellectual Property Policy** 
.. Collaborators acknowledge that the copyright in all new contributions will be retained by the copyright holder as independent works of authorship and that no contributor or copyright holder will be required to assign copyrights to the Project.  
.. Except as described in Section 7.c., all contributions to the Project are subject to the following:  
... Documentation will be received and made available by the Project under the Creative Commons Attribution 4.0 International License (available at [http://creativecommons.org/licenses/by/4.0/).](http://creativecommons.org/licenses/by/4.0/)  
... Any code contributed will be contributed and made available under a license approved as open by the Open Source Initiative. 
... The Project may seek to integrate and contribute back to other open source projects (“Upstream Projects”). In such cases, the Project will conform to all license requirements of the Upstream Projects, including dependencies, leveraged by the Project.  Upstream Project code contributions not stored within the Project’s main code repository will comply with the contribution process and license terms for the applicable Upstream Project. 
.. The SC may approve the use of an alternative license or licenses for inbound or outbound contributions on an exception basis. To request an exception, please describe the contribution, the alternative open source license(s), and the justification for using an alternative open source license for the Project. License exceptions must be approved by a two-thirds vote of the entire SC.  
.. Contributed files should contain license information, such as SPDX short form identifiers, indicating the open source license or licenses pertaining to the file. 
. **Amendments** 
.. This charter may be amended by a two-thirds vote of the entire SC and is subject to approval by LF Projects. 
